services:
  - type: web
    name: sql-practice-104k
    env: python
    rootDir: backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
